spring:
  application:
    name: SMSBackend
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.studentsmanagement.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug